services:
  django-ninja:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: performance_test_django_ninja
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=django-ninja-local-secret
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=testuser
      - DB_PASSWORD=testpassword
      - DB_NAME=testdb
